### ISSUE TITLE
Razer Tartarus Chroma V2

### ISSUE THREAD

**Issue by waytoomuchgaming** [DutchGraa/Razer-USB-tartarus#1]
Hi

I try to use your program, but i fail (i'm not tech-savvy, and editing python files is above what i can understand).
But maybe your program won't work with the V2 version of the Tartarus Chroma anyway ?
If it can, how can i use it as a simple remapper (i have no use for the default mapping) ?

**Comment by spipm** [comment]
Hi Altoholic,

I can try and rewrite parts tomorrow to create a simple remapper. But I would like to know what problems you're running in to.
Are you getting a specific error message or does nothing happen when you run `sudo python run.py`?
Also, are you on Linux?

**Comment by waytoomuchgaming** [comment]
That would be great :)
Yes, i use Linux (Xubuntu).

Here what i get:

```
User is pressing keys: 1
User released all buttons
User is pressing keys: 2
User released all buttons
User is pressing keys: 3
Performing cut..
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    ret = processData(data)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/process.py", line 39, in processData
    doCutzxcv()
NameError: global name 'doCutzxcv' is not defined

```

**Comment by waytoomuchgaming** [comment]
Button 3 and TBOTTOM give me error.
But i should remap the whole Tartarus first to have real life use of it... but i don't know how. Some things to change in process.py, i guess ?

**Comment by spipm** [comment]
Alright check it out. I moved mapping to remapconf.py for basic remapping.
Does this work for you?
If you need additional keys or key combinations let me know.

**Comment by waytoomuchgaming** [comment]
```
User is pressing keys: tbottom
Found key
Executing doCloseTab
^Z
[1]+  Arrêté                sudo python run.py
b@ordineuf:~/Téléchargements/tartarus/Razer-USB-tartarus-master$ sudo python run.py 
^CTraceback (most recent call last):
  File "run.py", line 36, in <module>
    releaseDevice(dev)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/usbkernel.py", line 27, in releaseDevice
    dev.attach_kernel_driver(interface)
  File "/home/b/.local/lib/python2.7/site-packages/usb/core.py", line 1089, in attach_kernel_driver
    interface)
  File "/home/b/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 906, in attach_kernel_driver
    _check(self.lib.libusb_attach_kernel_driver(dev_handle.handle, intf))
  File "/home/b/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

```



once i press the bottom button, it crash, then stop to do anything (i have to reboot the computer).
the usbrest thing don't seem to work, even if he says:


```
b@ordineuf:~/Téléchargements/tartarus/Razer-USB-tartarus-master/testing/usbreset$ sudo ./usbreset /dev/bus/usb/001/002 
Resetting USB device /dev/bus/usb/001/002
Reset successful
```

**Comment by waytoomuchgaming** [comment]
but all the other keys seem to work:

```
User is pressing keys: 1
Found key
Pressing a
qUser released all buttons
User is pressing keys: 2
Found key
Pressing a
qUser released all buttons
User is pressing keys: 3
Found key
Pressing a
qUser released all buttons
User is pressing keys: 4
Found key
Pressing a
qUser released all buttons
User is pressing keys: 5
Found key
Pressing a
qUser released all buttons
User is pressing keys: 6
Found key
Pressing b
bUser released all buttons
User is pressing keys: 7
Found key
Pressing b
bUser released all buttons
User is pressing keys: 8
Found key
Pressing b
bUser released all buttons
User is pressing keys: 9
Found key
Pressing b
bUser released all buttons
User is pressing keys: 10
Found key
Pressing b
bUser released all buttons
User is pressing keys: 11
Found key
Pressing c
cUser released all buttons
User is pressing keys: 12
Found key
Pressing c
cUser released all buttons
User is pressing keys: 13
Found key
Pressing c
cUser released all buttons
User is pressing keys: 14
Found key
Pressing c
cUser released all buttons
User is pressing keys: 15
Found key
Pressing c
cUser released all buttons
User is pressing keys: 1
Found key
Pressing a
qUser released all buttons
User is pressing keys: 2
Found key
Pressing a
qUser released all buttons
User is pressing keys: 3
Found key
Pressing a
qUser released all buttons
User is pressing keys: 4
Found key
Pressing a
qUser released all buttons
User is pressing keys: 5
Found key
Pressing a
qUser released all buttons
User is pressing keys: 6
Found key
Pressing b
bUser released all buttons
User is pressing keys: 7
Found key
Pressing b
bUser released all buttons
User is pressing keys: 8
Found key
Pressing b
bUser released all buttons
User is pressing keys: 9
Found key
Pressing b
bUser released all buttons
User is pressing keys: 10
Found key
Pressing b
bUser released all buttons
User is pressing keys: 11
Found key
Pressing c
cUser released all buttons
User is pressing keys: 12
Found key
Pressing c
cUser released all buttons
User is pressing keys: 13
Found key
Pressing c
cUser released all buttons
User is pressing keys: 14
Found key
Pressing c
cUser released all buttons
User is pressing keys: 15
Found key
Pressing c
cUser released all buttons
User is pressing keys: ttop
Found key
Executing doNewTab
^TUser released all buttons
User is pressing keys: ttop
Found key
Executing doNewTab
^TUser released all buttons
User is pressing keys: right
Found key
Pressing right
^[[CUser released all buttons
User is pressing keys: left
Found key
Pressing left
^[[DUser released all buttons
User is pressing keys: up
Found key
Pressing up
^[[AUser released all buttons
User is pressing keys: down
Found key
Pressing down
^[[BUser released all buttons
User is pressing keys: tbottom
Found key
Executing doCloseTab
^Z
[1]+  Arrêté                sudo python run.py

```

**Comment by spipm** [comment]
Hi again,

Thank you for testing! I changed the defaults to press page_up and page_down when pressing the thumb keys.

I think the problem was that I configured the tbottom key to perform CTRL+W, which causes the current window to close. And because you were pressing the keys in the current shell, it halted the Python program mid-execution. Weird that the USB reset program doesn't work btw, have to look into that.

The buttons should now work safely. Do try them out in different windows etc.

**Comment by spipm** [comment]
Btw, you can press 12-13-14-15-[top thumb button] at the same time (in order) as a "stop" command to safely shut down the script :)

**Comment by waytoomuchgaming** [comment]
It seem to work with no crash.
The 12-13-14-15 combo don't seem to do anything, i have to ctrl-c to get out of the program.
But the Tartarus is still usable after, i don't need to reboot.

Now for a new problem : i changed the mapping, to get what i will use in game.
The program won't start (but i expected it, as one of the key map is ").
Here is the output:

```
b@ordineuf:~/Téléchargements/tartarus/Razer-USB-tartarus-master$ sudo python run.py 
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from tartlib.process import *
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/process.py", line 6, in <module>
    from remapconf import *
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/remapconf.py", line 7
SyntaxError: Non-ASCII character '\xc3' in file /home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/remapconf.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by waytoomuchgaming** [comment]
here is my remapped file:

```
from tartlib.simulate import *


remapConfig = {

	"1":	"&",	# remap to letter
	"2":	"é",
	"3":	""",	
	"4":	"'",
	"5":	",",
	"6":	"(",
	"7":	"-",
	"8":	"è",
	"9":	"_",
	"10":	";",
	"11":	"ç",
	"12":	"à",
	"13":	")",
	"14":	"=",
	"15":	":",

	"ttop":		doPressPageUp, 	# remap to function for pressing multiple keys
	"tbottom":	doPressPageDown,

	"up":		"a",
	"right":	"up",
	"down":		"e",
	"left":		"down",

	"1-2-3":	"d" 		# boss mode: map multiple keys
							# don't use this yet: implementation is harder
}

```

**Comment by waytoomuchgaming** [comment]
Also, i plan to remap "ttop" to "!", and "tbottom" to "ù".
(I forgot to put them in)

Do i always use that syntax:
"existing_key": "key_i_want", ?

**Comment by spipm** [comment]
Yes that is the correct syntax. You should only change the mapping on the right like you're doing now.

Nice find! I didn't know you wanted to use unicode characters. Let me try and fix that hold on.

For the buttom combo, you need to press 12-..-15 and ttop (in order) :
User is pressing keys: 12-13-14-15-ttop
Exit command..

**Comment by waytoomuchgaming** [comment]
Oh, i forgot the ttop part of the "closing" combo, i'll try it again (edit: tested, it's working).

So, that's the way to properly use your software: opening a command line terminal, sudo the python run file, play the game, quit the game, using the closing combo in the terminal (or anywhere, i guess) ?

Yes, i use "weird" characters just because they are among the few not used in game (=> World of Warcraft).
Thus, they become precious for mapping ^^

**Comment by spipm** [comment]
I've added unicode support and all the characters from the config you described. The mapping config is a little bit less user friendly now, but it works.

For unicode characters, use:
"2":	[press_unicode, u"é"],
(replace é with the character you want)

For key combinations it's a bit harder. I have to manually put in the keys and combinations. Also, I need to configure the device to use specific keys. Have a look at mapping_keys in simulate.py. For example, for pressing "&" I need to press uinput.KEY_LEFTSHIFT and uinput.KEY_7. But those keys have to exist in the list of `device = uinput.Device([` or else the device won't support them.

> So, that's the way to properly use your software: opening a command line terminal, sudo the python run file, play the game, quit the game, using the closing combo in the terminal (or anywhere, i guess) ?

That is correct, should work. However, putting in support for unicode keys and keys like " was hard because I can't simulate keys like that directly: I have to simulate shift+' for example. On my keyboard, I need to simulate shift+' and then a space.
Also for unicode, I simulate ctrl+shift+u, then the typing of unicode hex, then an enter.

Oh by the way, some applications will hijack the ENTER key I use for unicode characters :( Here in Word everything works fine, but in Sublime it doesn't. I'd be glad to know if the keys work in your game!

**Comment by waytoomuchgaming** [comment]
Well, you lost me a bit (currently reading the wikipedia page about unicode ^^).

I replaced 2 things in the config file:
```
"ttop":		[press_unicode, u"!"], 	# remap to function for pressing multiple keys
	"tbottom":	[press_unicode, u"ù"],
```

And surprisingly, it works :)
But the rest don't work so well (no crash, but i don't have what i expected).
Here is what i have if i press each key in order of the config file: 7é% ù ;9)è°mçà0=M!ùqe

As i see the "a" i expected is a "q", it look like a difference between keyboards layout.
My keyboard is frFR, if that is of any help.

**Comment by waytoomuchgaming** [comment]
Maybe i should add: all the "weird" keys i intend to use are on my keyboard, as a single press. No need to combo anything for me (that's the point, as i will have to combo them a lot in the game, with shift, alt, ctrl, and all combination possible of them - 7 combinations total, with lead to 8 uses of a single key).

**Comment by spipm** [comment]
Oh dang, I wouldn't have guessed you had your keyboard set to french. That would require some extra work X-p

I may need to refactor some parts of the code to give it nicer configuration options and settings for different kinds of keyboards. Maybe I can do that tomorrow.

Some types of french keyboard are described here:
http://xahlee.info/kbd/french_keyboard_layout.html
Can you tell me what kind of french layout you have (Canadian French, French AZERTY, Bépo, ..) and what keys you need?

**Comment by waytoomuchgaming** [comment]
Ok, thank you :)

I use this one : https://images-na.ssl-images-amazon.com/images/I/91mu8mAnsCL._SL1500_.jpg

It's a "French AZERTY Layout", if i follow your link. But with more keys that the one of your link.

edit: "what keys i need"... well... all of them ? ^^
I don't use my regular keyboard (the one i linked) in game a lot. Mostly for out of action stuff (talking, using in game menus - with shortcuts, usually one letter shortcut).
I plan to use the Tartarus a lot, and all of his keys (which are the "weird" ones i listed).

**Comment by spipm** [comment]
Alright Altoholic, check it out :) I've refactored parts of the code to make it more flexible.

It doesn't "support" your french keyboard, but you can create your own mapping! Have a look at the Configuration section in the README. I hope it makes sense: you create psuedo-mapping in remap_config and give meaning to the mapping in mapping_meaning.

Note that you would still need to use the American style keyboard keys I think. For example, I see in the image of your keyboard that the 'z' is in the place of the 'w'. Now, let's say you want to use the "3" on the tartarus for the 'z'. You could do this:

In remap_config:

	"3":	"w",

Another example: I see the comma is under your 4-key. To create a comma binding, you could do this:

In remap_config:

	"3":	"comma",

Then in mapping_meaning:

	"comma":  CharMeaning(MEAN_COMBO, [uinput.KEY_LEFTSHIFT, uinput.KEY_4]),

Another cool thing: You can now easily configure a special key. I've configured the 11-key on the Tartarus as a special key. Try 11+14 for copy and 11+15 for paste :) Don't do this in your shell because it will press ctrl+c and quit the program.

**Comment by waytoomuchgaming** [comment]
I think it will be way harder than expected (as a lot of specials characters i plan to use are not on a Qwerty layout) ^^
Unless, maybe, i can use unicode everywhere ? So i don't have to make guesses about what key is where on a qwerty layout ?

Also, i plan to use that layout (https://upload.wikimedia.org/wikipedia/commons/1/17/LinuxUSKeyboard.png), is it ok ?
Strangely, i found a lot of different US qwerty layouts (even if the differences between them are small).

**Comment by waytoomuchgaming** [comment]
So, i tried a "full unicode approach", to avoid me being lost in layout translation, but it failed.
Here is my remap.py:
```
# -*- coding: utf-8 -*-

# This is the configuration for mapping from razor tartarus to some value
# You should only change values on the right
remap_config = {

	#FROM   #TO
	"1":	"&",
	"2":	"é",
	"3":	"²",	
	"4":	"'",
	"5":	",",
	"6":	"(",
	"7":	"-",
	"8":	"è",
	"9":	"_",
	"10":	";",
	"11":	"ç",
	"12":	"à",
	"13":	")",
	"14":	"=",
	"15":	":",

	"ttop":		"!",
	"tbottom":	"ù",

	"up":		"a",
	"right":	"up",
	"down":		"e",
	"left":		"down",

}
```

and my output.py:
```
# -*- coding: utf-8 -*-
import collections
import uinput

# press key normally
MEAN_PRESS = "press_normal"
# press unicode key
MEAN_PRESSU = "press_unicode"
# press combination
MEAN_COMBO = "press_combo"
# press combination and then a space
MEAN_COMBOS = "press_combo_space"
# use function
MEAN_FUNC = "press_function"


CharMeaning = collections.namedtuple('CharMeaning', ['kind', 'args'])


# This mapping gives meaning to the keys you decribed in the remapping
mapping_meaning = {

  # examples of normal key presses
 
  "up":     CharMeaning(MEAN_PRESS, uinput.KEY_UP),
  "down":   CharMeaning(MEAN_PRESS, uinput.KEY_DOWN),

  # example of unicode character

  "&": CharMeaning(MEAN_PRESSU, u"&"),
  "é": CharMeaning(MEAN_PRESSU, u"é"),
  "²": CharMeaning(MEAN_PRESSU, u"²"),
  "'": CharMeaning(MEAN_PRESSU, u"'"),
  ",": CharMeaning(MEAN_PRESSU, u","),
  "(": CharMeaning(MEAN_PRESSU, u"("),
  "-": CharMeaning(MEAN_PRESSU, u"-"),
  "è": CharMeaning(MEAN_PRESSU, u"è"),
  "_": CharMeaning(MEAN_PRESSU, u"_"),
  ";": CharMeaning(MEAN_PRESSU, u";"),
  "ç": CharMeaning(MEAN_PRESSU, u"ç"),
  "à": CharMeaning(MEAN_PRESSU, u"à"),
  ")": CharMeaning(MEAN_PRESSU, u")"),
  "=": CharMeaning(MEAN_PRESSU, u"="),
  ":": CharMeaning(MEAN_PRESSU, u":"),
  "!": CharMeaning(MEAN_PRESSU, u"!"),
  "ù": CharMeaning(MEAN_PRESSU, u"ù"),
  "a": CharMeaning(MEAN_PRESSU, u"a"),
  "e": CharMeaning(MEAN_PRESSU, u"e")

}
```

And the resulting error (who blocked the terminal window):
```
User is pressing keys: 2
Found keys in remap config
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    ret = processor.processData(data)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/process.py", line 53, in processData
    self.simulator.simulate(pressed_keys)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/device.py", line 31, in simulate
    self.press_unicode(meaning.args)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/device.py", line 61, in press_unicode
    self.device.emit_click(mapping_meaning[norm_char].args)
  File "/home/b/.local/lib/python2.7/site-packages/uinput/__init__.py", line 234, in emit_click
    ev_type, ev_code = event
ValueError: need more than 1 value to unpack

```

**Comment by waytoomuchgaming** [comment]
Trying a bit differently:

Remap.py:
```
# -*- coding: utf-8 -*-

# This is the configuration for mapping from razor tartarus to some value
# You should only change values on the right
remap_config = {

	#FROM   #TO
	"1":	"esperluette",
	"2":	"e aigu",
	"3":	"petit deux",	
	"4":	"apostrophe",
	"5":	"virgule",
	"6":	"parent gauche",
	"7":	"moins",
	"8":	"e grave",
	"9":	"souligne",
	"10":	"point virgule",
	"11":	"cedille",
	"12":	"a accent",
	"13":	"parent droite",
	"14":	"egal",
	"15":	"deux points",

	"ttop":		"exclamation",
	"tbottom":	"u accent",

	"up":		"a",
	"right":	"up",
	"down":		"e",
	"left":		"down",

}
```
Output.py:
```
# -*- coding: utf-8 -*-
import collections
import uinput

# press key normally
MEAN_PRESS = "press_normal"
# press unicode key
MEAN_PRESSU = "press_unicode"
# press combination
MEAN_COMBO = "press_combo"
# press combination and then a space
MEAN_COMBOS = "press_combo_space"
# use function
MEAN_FUNC = "press_function"


CharMeaning = collections.namedtuple('CharMeaning', ['kind', 'args'])


# This mapping gives meaning to the keys you decribed in the remapping
mapping_meaning = {

  # examples of normal key presses
 
  "up":     CharMeaning(MEAN_PRESS, uinput.KEY_UP),
  "down":   CharMeaning(MEAN_PRESS, uinput.KEY_DOWN),

  # example of unicode character

  "esperluette": CharMeaning(MEAN_PRESSU, u"&"),
  "e aigu": CharMeaning(MEAN_PRESSU, u"é"),
  "petit deux": CharMeaning(MEAN_PRESSU, u"²"),
  "apostrophe": CharMeaning(MEAN_PRESSU, u"'"),
  "virgule": CharMeaning(MEAN_PRESSU, u","),
  "parent gauche": CharMeaning(MEAN_PRESSU, u"("),
  "moins": CharMeaning(MEAN_PRESSU, u"-"),
  "e grave": CharMeaning(MEAN_PRESSU, u"è"),
  "souligne": CharMeaning(MEAN_PRESSU, u"_"),
  "point virgule": CharMeaning(MEAN_PRESSU, u";"),
  "cedille": CharMeaning(MEAN_PRESSU, u"ç"),
  "a accent": CharMeaning(MEAN_PRESSU, u"à"),
  "parent droite": CharMeaning(MEAN_PRESSU, u")"),
  "egal": CharMeaning(MEAN_PRESSU, u"="),
  "deux points": CharMeaning(MEAN_PRESSU, u":"),
  "exclamation": CharMeaning(MEAN_PRESSU, u"!"),
  "u accent": CharMeaning(MEAN_PRESSU, u"ù"),
  "a": CharMeaning(MEAN_PRESSU, u"a"),
  "e": CharMeaning(MEAN_PRESSU, u"e")

}




```

The error:
```
User is pressing keys: 1
Found keys in remap config
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    ret = processor.processData(data)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/process.py", line 53, in processData
    self.simulator.simulate(pressed_keys)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/device.py", line 31, in simulate
    self.press_unicode(meaning.args)
  File "/home/b/Téléchargements/tartarus/Razer-USB-tartarus-master/tartlib/device.py", line 61, in press_unicode
    self.device.emit_click(mapping_meaning[norm_char].args)
KeyError: '2'
```

**Comment by spipm** [comment]
Ah ok, good one. Yes you did it right the second time. The problem was that the code that entered the unicode characters was using the mapping from mapping_meaning, so it tried pressing mapping_meaning["2"] for the key 2 but it wasn't there.

I've given the hex characters a custom table so you don't have to worry about that any more. The config you pasted above should work fine now :) Let me know again! And thanks for all the testing.

**Comment by waytoomuchgaming** [comment]
It's nearly working :)

I had to replace the "a" with a "q" in remap.py, because layout.

I used ² instead of ", fearing the fact that you have to use multiple keys to emulate ". I prefer to avoid anything that is not a single key press, because i will heavily use modifiers with the output of the Tartarus, and i wary that all these modifiers can conflict with the ones coming from the Tartarus, if i use them. But maybe i'm wrong and, whatever i chose, the Tartarus will always send only a single keypress in output ? If yes, then i'll prefer to use " instead of ² (because it's one of the standard key of the game, i don't need to remap it in game).

And then i have the 15th key, supposedly ":", who do "".
This is basically the last problem (once i'll got a clear view of how the ² or " use).

**Comment by spipm** [comment]
I would use 
    `CharMeaning(MEAN_COMBO, [uinput.KEY_LEFTSHIFT, uinput.KEY_3]),`
    (from the image you sent, the double quote is under the 3 key)
Instead of the MEAN_PRESSU thing because MEAN_PRESSU is actually doing more key presses than MEAN_COMBO. So MEAN_COMBO should be safer.

Also, note that if you want to type the "-character in double quotes it needs to be like: "\\""

I don't know if the keyboard will affect modifiers in the game.

Okay, I think I know why it's giving you the weird character. When you use MEAN_PRESSU, the keyboard simulator will first press ctrl+shift+u, then simulate pressing the hex characters, then the enter key. The semicolon has the hex value 3a, so it will first press the 3, and then the 'a', and then enter. But on your keyboard it will press the q instead of the a, like you mentioned.
Can you try fixing the keys in tartlib/mapping/hexkeys.py to match your keyboard? I think that should fix the unicode characters. So for example:
mapping_hexkeys = {
  "a": uinput.KEY_Q,
..etc

**Comment by waytoomuchgaming** [comment]
Mmhh... so i should rewrite as much as MEAN_PRESSU to MEAN_COMBO i can, to avoid futur problems. Oh well, i'll try as it is now first ^^

But yes, all these simulated keypress wary me a bit, as, for exemple, "return" is the keypress to open the chat. So, if the game ever catch that one, it mean that everything else will be sent to the ingame chat, not to the "action part" of the game. But maybe i worry for nothing. I hope to.

For hexkeys.py, i got a problem: a become q, and vice versa. All the others letters (b, c, d, e, f) stay unchanged. But the numbers on a Azerty keyboard are the upper part of the key. You don't have them with a simple keypress, opposite to a Qwerty keyboard. So, for exemple, if i want a 0, on my Azerty keyboard, i need to press shift+à, and i quickly run into problems, as you can see in the rewritten file (because i'm sure those "weird" characters won't pass as they are):

```
import uinput

mapping_hexkeys = {
  "a": uinput.KEY_Q,
  "b": uinput.KEY_B,
  "c": uinput.KEY_C,
  "d": uinput.KEY_D,
  "e": uinput.KEY_E,
  "f": uinput.KEY_F,
  "0": uinput.KEY_à,
  "1": uinput.KEY_&,
  "2": uinput.KEY_é,
  "3": uinput.KEY_",
  "4": uinput.KEY_',
  "5": uinput.KEY_(,
  "6": uinput.KEY_-,
  "7": uinput.KEY_è,
  "8": uinput.KEY__,
  "9": uinput.KEY_ç
}
```

**Comment by spipm** [comment]
Oh no that's not going to work. The keys need to exist in this file:
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h
I think you can just leave the number-keys in hexkeys.py as they were and it should work.

**Comment by waytoomuchgaming** [comment]
But i realize i only needed the a to be changed to correct the current problem. So i did, and all seem ok now. Time to test it in game ^^;;;;

**Comment by spipm** [comment]
Ok let me know I'm really interested in how it works in a game!

**Comment by waytoomuchgaming** [comment]
Ok: it's not working at all ^^
The game catch every keypress made by the program, so i end up with no usable key at all. Only the ones that use return open the chat.

**Comment by spipm** [comment]
Hahaha oh man ;) Well sorry man, this is as far as I can go without writing some kind of kernel driver. The direct keypresses or combo keys also not working?

**Comment by waytoomuchgaming** [comment]
Also not.
Well, i can assign them ingame (as opposite to the unicode ones, who always end up as modifiers+u), but i can't use them afterward.

So sad that's not working, you were my last hope (i dabbled with kxbcomp a bit, ending with the exact layout i needed on my Tartarus, but had weird side effects when i used my modified file, making it unusable ingame).

Thank you anyway for your patience :)

**Comment by spipm** [comment]
Man, that sucks. Have you asked Blizzard for support on this issue? Maybe they can help with, or give more info about how the game handles these things. Good luck on your journey! There must be a way.

**Comment by waytoomuchgaming** [comment]
Thank you! :)

**Comment by waytoomuchgaming** [comment]
Or maybe... if i can manage to use only MEAN_PRESS, it mean there is no multiple keypress, right ?
Also, i should only use keys of the qwerty layout that have a direct keypress on the azerty layout... mmhh... it's unlikely i found 21 of them.

Oh wait, no, a, e, and the direction arrows were MEAN_PRESS, and none of them worked.
Ok, i'm done ^^
